#!/usr/bin/env bash
set -e

NODE_FIRST_REF=v0.9.0
NODE_LAST_REF=HEAD

LIBUV_FIRST_REF=node-v0.9.0
LIBUV_LAST_REF=HEAD

BASEDIR=$PWD

echo Node.js contribution data as of $(date)

echo

if [ -d node ]
then
  cd node
  git fetch --all
  cd -
else
  git clone https://github.com/joyent/node.git
fi

if [ -d libuv ]
then
  cd libuv
  git fetch --all
  cd -
else
  git clone https://github.com/joyent/libuv.git
fi

echo Node patches:
echo

cd $BASEDIR/node

declare -a CONTRIBUTORS=()

git log --all --pretty=format:%aN $NODE_FIRST_REF..$NODE_LAST_REF | sort | uniq -c | sort -nr | {\
  while read CONTRIB_LINE
  do
    echo $CONTRIB_LINE
    CONTRIB_NAME=$(echo $CONTRIB_LINE | awk '{sub($1,"");print}')
    CONTRIBUTORS+=("$CONTRIB_NAME")
  done

  echo
  echo Node LoC:
  echo

  {\
    for CONTRIB_NAME in "${CONTRIBUTORS[@]}"
    do
      CLEANED_NAME=$(echo $CONTRIB_NAME)
      echo $(git log --all --patch-with-stat --author="$CLEANED_NAME" $NODE_FIRST_REF..$NODE_LAST_REF | wc -l) $CLEANED_NAME
    done
  } | sort -nr

  echo
  echo Node lines added or changed:
  echo
  
  {\
    for CONTRIB_NAME in "${CONTRIBUTORS[@]}"
    do
      CLEANED_NAME=$(echo $CONTRIB_NAME)
      echo $(git log --all --oneline --shortstat --author="$CLEANED_NAME" $NODE_FIRST_REF..$NODE_LAST_REF | grep "^ " | awk '{print $4}' | paste -sd+ - | bc) $CLEANED_NAME
    done
  } | sort -nr
}

echo

#########################

echo libuv patches:
echo

cd $BASEDIR/libuv

declare -a CONTRIBUTORS=()

git log --pretty=format:%aN $LIBUV_FIRST_REF..$LIBUV_LAST_REF | sort | uniq -c | sort -nr | {\
  while read CONTRIB_LINE
  do
    echo $CONTRIB_LINE
    CONTRIB_NAME=$(echo $CONTRIB_LINE | awk '{sub($1,"");print}')
    CONTRIBUTORS+=("$CONTRIB_NAME")
  done

  echo
  echo libuv LoC:
  echo

  {\
    for CONTRIB_NAME in "${CONTRIBUTORS[@]}"
    do
      CLEANED_NAME=$(echo $CONTRIB_NAME)
      echo $(git log --patch-with-stat --author="$CLEANED_NAME" $LIBUV_FIRST_REF..$LIBUV_LAST_REF | wc -l) $CLEANED_NAME
    done
  } | sort -nr

  echo
  echo libuv lines added or changed:
  echo
  
  {\
    for CONTRIB_NAME in "${CONTRIBUTORS[@]}"
    do
      CLEANED_NAME=$(echo $CONTRIB_NAME)
      echo $(git log --oneline --shortstat --author="$CLEANED_NAME" $LIBUV_FIRST_REF..$LIBUV_LAST_REF | grep "^ " | awk '{print $4}' | paste -sd+ - | bc) $CLEANED_NAME
    done
  } | sort -nr
}
