#!/usr/bin/env sh
set -e

echo Node.js contribution data as of $(date)

git submodule update --init

cd node

declare -a CONTRIBUTORS=()

echo Node patches:
echo

git log --pretty=format:%aN v0.9.0..HEAD | sort | uniq -c | sort -nr | {\
  while read CONTRIB_LINE
  do
    echo $CONTRIB_LINE
    CONTRIB_NAME=$(echo $CONTRIB_LINE | awk '{sub($1,"");print}')
    CONTRIBUTORS+=("$CONTRIB_NAME")
  done

  echo
  echo Node LoC:
  echo

  {\
    for CONTRIB_NAME in "${CONTRIBUTORS[@]}"
    do
      CLEANED_NAME=$(echo $CONTRIB_NAME)
      echo $(git log --patch-with-stat --author="$CLEANED_NAME" v0.9.0..HEAD | wc -l) $CLEANED_NAME
    done
  } | sort -nr
}

cd -




# echo libuv patches:
# pushd libuv
#   git shortlog -ns node-v0.9.0..HEAD | while read contributor_line ; do
#     echo $contributor_line
#   done
# popd
# 
# echo Node LoC:
# pushd node
#   
# popd
# 
# echo libuv LoC:
# pushd libuv
#   
# popd
